# This is the YAML file for Continuous Integration of the Ph2_ACF Middleware
# This is a prototype version!!
# Author: Nikkie Deelen (CERN/KIT)

before_script:
   ### Do we need to install everything all the time?? ###

   #- wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
   #- sudo yum install devtoolset-2
   #- sudo ln -s /opt/rh/devtoolset-2/root/usr/bin/* /usr/local/bin/
   #- hash -r
   #- wget http://svnweb.cern.ch/trac/cactus/export/28265/tags/ipbus_sw/uhal_2_3_0/scripts/release/cactus.slc6.x86_64.repo
   #- sudo cp cactus.slc6.x86_64.repo /etc/yum.repos.d/cactus.repo
   #- sudo yum clean all
   #- sudo yum groupinstall uhal
   #- sudo yum install root
 
   ### We definetely need to source everytime ###

   - source setup.sh
  
build_Ph2_ACF:
   stage:
      - build

   script: 
      - make
